# Generated by Django 4.2.6 on 2023-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.CharField(choices=[('none', 'None'), ('before_15', '15 minutes before'), ('before_30', '30 minutes before'), ('before_1d', '1 Day before')], default='none', max_length=17),
        ),
    ]
