# Generated by Django 4.2.6 on 2023-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('task_type', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=9)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('detailed_info', models.CharField(blank=True, max_length=128)),
                ('place', models.CharField(blank=True, max_length=64)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='togather/uploads/')),
                ('reminder', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[(None, 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default=None, max_length=7)),
            ],
        ),
    ]
