# Generated by Django 4.2.6 on 2023-11-24 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('bio', models.CharField(blank=True, max_length=128)),
                ('picture', models.ImageField(default='blank-profile-picture.jpg', upload_to='profile_pictures')),
                ('country', models.CharField(choices=[('turkey', 'Turkey')], default='turkey', max_length=64)),
                ('city', models.CharField(choices=[('ankara', 'Ankara')], default='ankara', max_length=64)),
                ('interest', models.CharField(choices=[('none', 'None'), ('music', 'Music'), ('theatre', 'Theatre'), ('movies', 'Movies'), ('literacy', 'Literacy')], default='none', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
